### ISSUE TITLE
analysis_cell should be saved even when running aqm.analysis_cell("some_old_path")

### ISSUE THREAD

**Issue by SamuelDeleglise** [kyrylo-gr/quanalys#13]
I think I fixed this behavior by changing lin 143 of acquisition_manager_notebook.py from:
`self.analysis_cell_str = None`  ==> `self.analysis_cell_str = cell`

Just wanted to be sure this is the right way of fixing it...

**Comment by kyrylo-gr** [comment]
Now there is function `save_analysis_cell` and `save_fig_and_analysis_cell`
