### ISSUE TITLE
The analysis_cell is not what we want when analysis is run from spyder

### ISSUE THREAD

**Issue by SamuelDeleglise** [kyrylo-gr/quanalys#16]
We only get the following (the line that ends up being executed in ipython by spyder)

`runcell(0, 'C:/Users/CryoPc/My Drive/mecaflux/measurements/Cooldown_2022_05_30_g_fluxonium_v1_is_back/untitled1.py')`

... I know that it makes some sense, but it would be nice if there was a simple workaround...

**Comment by SamuelDeleglise** [comment]
After digging a bit, I found this... 

```
import inspect

def get_current_code():
    return inspect.getsource(inspect.getouterframes(inspect.currentframe())[1][0])
```

To be checked in various environments, but that seems to give the cell content in a jupyter notebook and the whole file content in a spyder execution...

**Comment by 4cd87a** [comment]
This solution works only to get code that was run before `get_current_code()`
![image](https://user-images.githubusercontent.com/52211599/211939764-e1e0e678-fb92-429f-a117-ea115ff59c3f.png)

The current solution works with jupyter notebook and if you execute code inside vscode with `#%%`.

P.s. I think if someone uses spyder to execute an analysis, he deals with bigger problems that this one
